server:
  port: 8082
spring:
  application:
    name: ms-books-payments
  sql:
      init:
        mode: always
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
 datasource:
    url: jdbc:mysql://relatospapel-payments.ccfxzc0p3xna.us-east-1.rds.amazonaws.com:3306/relatospapel-payments
    username: admin
    password: adminrelatos
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init: DEBUG
