server:
  port: 8081
spring:
  sql:
      init:
        mode: always
  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: '20'
        max-page-size: '2000'
      sort:
        sort-parameter: sort
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  application:
    name: ms-books-catalogue
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init: DEBUG
      apache:
          tomcat:
            util:
              net: DEBUG
              threads: DEBUG