server:
  port: '8761'
spring:
  application:
    name: eureka-server
eureka:
  client:
    fetchRegistry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
